name: Build and Deploy to ACR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.firstcontainerappacracr123.azurecr.io }}
        username: ${{ secrets.firstcontainerappacracr123 }}
        password: ${{ secrets.g+458osvfnWNp6FAMv36hDt8d0dI7/z4cFuE9YOiFj+ACRBhBh6v }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/firstcontainerappacracr123:${{ github.sha }} .
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/firstcontainerappacracr123:${{ github.sha }}

    - name: Log out from Azure Container Registry
      run: docker logout ${{ secrets.firstcontainerappacracr123}}
